project:
  type: website
  output-dir: docs

website:
  title: "SamStruthersCSU"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - current.qmd
      - previous.qmd
      - resume.qmd
      - music.qmd
      - photography.qmd
      - contact.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

